# CARGA DE NUESTROS DATOS

In [3]:
#Importamos Pandas

import pandas as pd

In [4]:
#Procedemos a leer nuestro dataframe y le asignamos el valor df

df = pd.read_csv('retail.csv')

df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [5]:
df.shape

(1000, 9)

In [6]:
#Procedemos a ver los tipos de datos de las columnas

print("--- TIPOS DE DATOS ---")
print(df.info())
print()

print("--- FILAS Y COLUMNAS ---")
print(df.shape)

--- TIPOS DE DATOS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   object
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB
None

--- FILAS Y COLUMNAS ---
(1000, 9)

In [7]:
#Extraemos estadisticas descriptivas de nuestro Dataframe
df.describe().round(2)

       Transaction ID      Age  Quantity  Price per Unit  Total Amount
count         1000.00  1000.00   1000.00         1000.00        1000.0
mean           500.50    41.39      2.51          179.89         456.0
std            288.82    13.68      1.13          189.68         560.0
min              1.00    18.00      1.00           25.00          25.0
25%            250.75    29.00      1.00           30.00          60.0
50%            500.50    42.00      3.00           50.00         135.0
75%            750.25    53.00      4.00          300.00         900.0
max           1000.00    64.00      4.00          500.00        2000.0

In [8]:
#Buscamos filas duplicadas o datos vacios

print("--- DATOS VACÍOS ---")
print(df.isnull().sum())

print("\n--- FILAS DUPLICADAS ---")
print(df.duplicated().sum())

--- DATOS VACÍOS ---
Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

--- FILAS DUPLICADAS ---
0

In [9]:
#Aunque no tenemos datos vacios ni filas duplicadas, por procedimiento vamos a procesarlos de igual manera

df = df.drop_duplicates()

df = df.fillna(0)

In [10]:
#Vemos nuestros datos nuevamente

df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [11]:
#Procedemos a crear el archivo de datos limpios

df.to_csv('Retail_Limpio.csv', index=False)

# FIJAMOS NUESTROS OBJETIVOS

## Impacto de las Caracteristicas del cliente en la Facturación

### Hipotesis

El perfil demográfico de los clientes influye significativamente en el volumen de facturación, existiendo segmentos específicos que generan un mayor ticket promedio que otros

# Objetivo 1: ¿Varía el ticket promedio significativamente entre hombres y mujeres?

In [12]:
#Arreglamos nuestros datos

Hombres = df[df['Gender'] == 'Male']

print('Total de hombres:', len(Hombres))
Hombres[['Date', 'Gender', 'Total Amount']].head(10)

Total de hombres: 490

          Date Gender  Total Amount
0   2023-11-24   Male           150
2   2023-01-13   Male            30
3   2023-05-21   Male           500
4   2023-05-06   Male           100
6   2023-03-13   Male            50
7   2023-02-22   Male           100
8   2023-12-13   Male           600
10  2023-02-14   Male           100
11  2023-10-30   Male            75
12  2023-08-05   Male          1500

In [13]:
#Arreglamos nuestros datos

Mujeres = df[df['Gender'] == 'Female']

print('Total de Mujeres:', len(Mujeres))
print()
Mujeres[['Date', 'Gender', 'Total Amount']].head(10)

Total de Mujeres: 510

          Date  Gender  Total Amount
1   2023-02-27  Female          1000
5   2023-04-25  Female            30
9   2023-10-07  Female           200
14  2023-01-16  Female          2000
16  2023-04-22  Female           100
17  2023-04-30  Female            50
18  2023-09-16  Female            50
20  2023-01-14  Female           500
22  2023-04-12  Female           120
23  2023-11-29  Female           300

In [14]:
ticket_genero = df.groupby('Gender')['Total Amount'].mean().round(2)
print("--- Ticket Promedio por Género ---")
print(ticket_genero)

--- Ticket Promedio por Género ---
Gender
Female    456.55
Male      455.43
Name: Total Amount, dtype: float64

# Objetivo 2: ¿Cómo influye la edad de manera directa en la elección de la categoría del producto?

In [15]:

Adultos_Menores = df[df['Age'] <= 40 ]


print('Total de menores de 40:', len(Adultos_Menores))	

print()



Adultos_Menores[['Date', 'Gender', 'Total Amount']].head(10)

Total de menores de 40: 466

          Date  Gender  Total Amount
0   2023-11-24    Male           150
1   2023-02-27  Female          1000
3   2023-05-21    Male           500
4   2023-05-06    Male           100
7   2023-02-22    Male           100
10  2023-02-14    Male           100
11  2023-10-30    Male            75
12  2023-08-05    Male          1500
15  2023-02-17    Male          1500
16  2023-04-22  Female           100

In [17]:
Adultos_Mayores = df[df['Age'] > 40 ]

print('Total de mayores de 40:', len(Adultos_Mayores))

print()


Adultos_Mayores[['Date', 'Gender', 'Total Amount']].head(10)

Total de mayores de 40: 534

          Date  Gender  Total Amount
2   2023-01-13    Male            30
5   2023-04-25  Female            30
6   2023-03-13    Male            50
8   2023-12-13    Male           600
9   2023-10-07  Female           200
13  2023-01-17    Male           120
14  2023-01-16  Female          2000
17  2023-04-30  Female            50
18  2023-09-16  Female            50
20  2023-01-14  Female           500

In [18]:
ticket_promedio_menores = Adultos_Menores['Total Amount'].mean().round(2)

ticket_promedio_mayores = Adultos_Mayores['Total Amount'].mean().round(2)

print("Ticket promedio de mayores de 40:", ticket_promedio_mayores)
print("Ticket promedio de menores de 40:", ticket_promedio_menores)

Ticket promedio de mayores de 40: 425.29
Ticket promedio de menores de 40: 491.19